In [25]:
from engine import PatentRetrievalService

In [26]:
service = PatentRetrievalService('../data.txt')

Batches: 100%|██████████| 149/149 [02:00<00:00,  1.24it/s]


In [27]:
keywords = ["enzymes"]

In [ ]:
# Balanced mode
results = service.retrieve_patents(keywords, precision_recall_balance=0.5)

c:\Users\SamOz.py\OneDrive\Documents\VSCode\datenna\src\engine.py:81: RuntimeWarning: invalid value encountered in power
  adjusted_scores = np.power(avg_similarities, power)


In [32]:
# High recall mode (more results, broader matches)
high_recall_results = service.retrieve_patents(keywords, precision_recall_balance=0.0)
high_recall_results

KeyboardInterrupt: 

In [30]:
# High precision mode (fewer, more relevant results)
high_precision_results = service.retrieve_patents(keywords, precision_recall_balance=0.51)

high_precision_results

{'retrieved_patents': [],
 'metadata': {'keywords': ['enzymes'],
  'total_matches': 0,
  'precision_recall_balance': 0.51,
  'embedding_model': 'paraphrase-multilingual-MiniLM-L12-v2'}}

In [33]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
model_name = 'paraphrase-multilingual-MiniLM-L12-v2'

dataset_path = '../data.txt'
with open(dataset_path, 'r', encoding='utf-8') as f:
        abstracts = [line.strip() for line in f if line.strip()]

embedding_model = SentenceTransformer(model_name)

In [34]:
embeddings = embedding_model.encode(sentences=abstracts, show_progress_bar=True)

Batches: 100%|██████████| 149/149 [02:02<00:00,  1.22it/s]


In [35]:
faiss.normalize_L2(embeddings)

In [36]:
dimension = embeddings.shape[1]
index = faiss.IndexFlatIP(dimension)  # Inner Product index for cosine similarity
index.add(embeddings)

In [37]:
keyword = ["enzymes", "medical"]
keyword_embedding = embedding_model.encode(keyword)

In [38]:
faiss.normalize_L2(keyword_embedding)

In [39]:
distances, indices = index.search(keyword_embedding, k=len(abstracts))

In [40]:
avg_similarities = np.mean(distances, axis=0)

In [41]:
avg_similarities

array([ 0.5473508 ,  0.5322075 ,  0.5303291 , ..., -0.13469458,
       -0.13983792, -0.16494924], dtype=float32)

In [44]:
np.power(avg_similarities, 1)

array([ 0.5473508 ,  0.5322075 ,  0.5303291 , ..., -0.13469458,
       -0.13983792, -0.16494924], dtype=float32)

In [50]:
avg_similarities[np.where(avg_similarities > 0.3)]

array([0.5473508 , 0.5322075 , 0.5303291 , 0.5107071 , 0.49691194,
       0.4867241 , 0.48271564, 0.4687717 , 0.4609985 , 0.4597147 ,
       0.45770788, 0.45380682, 0.45097536, 0.44880974, 0.4477414 ,
       0.4432252 , 0.44170278, 0.44083282, 0.43920004, 0.43526053,
       0.43474   , 0.43215084, 0.4301644 , 0.42623448, 0.4255086 ,
       0.42332646, 0.42265904, 0.4217047 , 0.41982636, 0.41839686,
       0.4174727 , 0.41535997, 0.4148507 , 0.41394272, 0.41212144,
       0.41044456, 0.4096312 , 0.40920544, 0.40857947, 0.4062822 ,
       0.40531373, 0.40425456, 0.403572  , 0.40342462, 0.403158  ,
       0.40250048, 0.40165722, 0.4001411 , 0.39964175, 0.39923677,
       0.39849365, 0.39809573, 0.39635354, 0.3933278 , 0.3927662 ,
       0.39216274, 0.39150548, 0.39143682, 0.3911968 , 0.39077228,
       0.38970694, 0.38692623, 0.38505572, 0.38448495, 0.38443506,
       0.3839057 , 0.38362128, 0.3832167 , 0.38294047, 0.38091397,
       0.37976846, 0.3775639 , 0.37732363, 0.37696707, 0.37643